version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - run:
          name: Install Bundler
          command: gem install bundler
      - run:
          name: Install dependencies
          command: bundle install
      - run:
          name: Build Jekyll site
          command: bundle exec jekyll build

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build      version: 2.1
      
      jobs:
        build:
          docker:
            - image: circleci/ruby:2.7
          steps:
            - checkout
            - run:
                name: Install Bundler
                command: gem install bundler
            - run:
                name: Install dependencies
                command: bundle install
            - run:
                name: Build Jekyll site
                command: bundle exec jekyll build
      
      workflows:
        version: 2
        build_and_deploy:
          jobs:
            - build